---
  - name: HAProxy | Install HAproxy
    package:
      name: haproxy
      state: present

  - name: HAProxy | Add haprports to firewalld
    firewalld:
      port: "{{ item }}"
      zone: public
      permanent: Yes
      state: enabled
    with_items:
      - 80/tcp
      - 7000/tcp

  - name: HAProxy | Add haprports to firewalld
    firewalld:
      rich_rule: rule protocol value="vrrp" accept
      zone: public
      permanent: Yes
      state: enabled

  - name: HAProxy | Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: HAProxy | Copy haproxy.cfg for Patronig for balancing patroni
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      force: Yes
    notify: enable_haproxy
    when: inventory_hostname == 'haproxy1'
  
  - name: HAProxy | Install Keepalived
    package:
      name: keepalived
      state: present
    when: 
      - inventory_hostname == 'haproxy2'
    
  - name: HAProxy | Install Keepalived
    package:
      name: keepalived
      state: present
    when: 
      - inventory_hostname == 'haproxy3'

  - name: HAProxy | Copy keepalived configs to master balancer
    template:
      src: master_keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      force: Yes
    notify: enable_keepalived
    when: 
      - inventory_hostname == 'haproxy2'

  - name: HAProxy | Copy keepalived configs to slave balancer
    template:
      src: slave_keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      force: Yes
    notify: enable_keepalived
    when: 
      - inventory_hostname == 'haproxy3'
    
  - name: HAProxy | Copy haproxy configs for load balancing
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      force: Yes
    notify: enable_haproxy
    when: 
      - inventory_hostname == 'haproxy2'

  - name: HAProxy | Copy haproxy configs for load balancing
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      force: Yes
    notify: enable_haproxy
    when: 
      - inventory_hostname == 'haproxy3'
...

