---
  - name: Patroni | configure | Configure patroni systemd service file
    template:
      src: patroni.service.j2
      dest: /etc/systemd/system/patroni.service

  - name: Patroni | configure | Create patroni directories
    file:
      path: "{{ item }}"
      state: directory
      owner: postgres
      group: postgres
      mode: 0700
    with_items:
      - /var/data/base
      - /etc/patroni/

  - name: Patroni | configure | Copy patroni config file
    template:
      src: patroni.yml.j2
      dest: /etc/patroni/patroni.yml
      owner: postgres
      group: postgres

  - name: Patroni | configure | Start patroni cluster
    systemd:
      name: patroni
      state: restarted
      daemon_reload: True
      enabled: true

  - name: Add database user taiga
    postgresql_user:
      login_host: 192.168.10.120
      port: 5000
      login_user: postgres
      login_password: gfhjkm
      name: taiga
      password: taiga
      state: present

    
  - name: Add database taiga with owner taiga
    postgresql_db:
      login_host: 192.168.10.120
      port: 5000
      login_user: postgres
      login_password: gfhjkm
      name: taiga
      owner: taiga
      state: present
...