---
- name: Consul | configuration | Configure systemd service file for Consul 
  template:                    
    src: consul.service.j2     
    dest: /etc/systemd/system/consul.service

- name: Consul | configuration | Configure Consul
  template:                    
    src: consul.json.j2        
    dest: /etc/consul.d/consul.json 
    owner: consul              
    group: consul              
  notify:
    - start consul 

- name: Consul | configuration | Add consul ports to firewalld
  firewalld:
      port: "{{ item }}"
      zone: public
      permanent: Yes
      state: enabled
  with_items:
      - 8500/tcp

...