---
  - name: Rabbitmq | main | Install epel-release
    package:
      name: epel-release
      state: present
    
  - name: Rabbitmq | main | Install rabbitmq-server
    dnf:
      name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.3/rabbitmq-server-3.8.3-1.el8.noarch.rpm
      state: present
    notify: restart_rabbitmq
...
