---
  - name: Rabbimq | main | Add rabbitmq ports to firewalld
    firewalld:
      port: "{{ item }}"
      zone: public
      permanent: Yes
      state: enabled
    with_items:
      - 5672/tcp
      - 15672/tcp

  - name: Rabbimq | main | Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded
   
  - name: Rabbitmq | main | Install rabbitmq-server
    dnf:
      name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.3/rabbitmq-server-3.8.3-1.el8.noarch.rpm
      state: present

  - name: Rabbitmq | main | Start rabbitmq-server
    service:
      name: rabbitmq-server
      state: started

  - name: Rabbitmq | main | Enables the rabbitmq_management plugin
    rabbitmq_plugin:
      names: rabbitmq_management
      state: enabled

  - name: Rabbitmq | main | Add taiga vhost
    rabbitmq_vhost:
      name: /taiga
      state: present

  - name: Rabbitmq | main | Add taiga user
    rabbitmq_user:
      user: taiga
      password: PASSWORD_FOR_EVENTS
      vhost: /taiga
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
  
...
