---
  - name: Monitoring | nodexporter | Download node_exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
      dest: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz

  - name: Monitoring | nodexporter | Extract node_exporter
    unarchive:
      src: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
      dest: /usr/local/bin
      extra_opts: [--strip-components=1]
    
  - name: Monitoring | nodexporter | Copy config file
    template:
      src: node_exporter
      dest: /etc/sysconfig/node_exporter

  - name: Monitoring | nodexporter | Copy systemd service
    template:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service

  - name: Monitoring | nodexporter | Daemon reload
    systemd:
      name: node_exporter
      state: restarted
      daemon_reload: Yes
      enabled: Yes    
...