---
  - name: Clone git taiga backend repo
    git:
      repo: https://github.com/taigaio/taiga-back.git
      dest: ~/taiga-back
      clone: Yes

  - name: Install pip requirements
    pip:
      requirements: ~/taiga-back/requirements.txt
      virtualenv: ~/taiga
      virtualenv_command: virtualenv-3.6
    
  - name: Copy taiga local.py config file
    template:
      src: local.py.j2
      dest: ~/taiga-back/settings/local.py
      owner: taiga
      group: wheel
      mode: '0644'
    
...