---
  - name: Taiga install | install-software | Install the 'Development tools' package group
    dnf:
      name: '@Development tools'
      state: present
  
  - name: Install PostgreSQL Repository
    dnf:
      name:  https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present

  - name: Disable the built-in PostgreSQL module
    command: dnf -qy module disable postgresql

  - name: Install psql
    package:
      name: postgresql11
      state: present

  - name: Taiga install | install-software | Install required packages
    package:
      name: "{{ taiga_packages }}"
      state: present
    register: package_results
    retries: 3
    until: package_results is success

  - name: Taiga install | install-software | Install Node.js Yum Repository
    shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -

  - name: Taiga install | install-software | Install Node.js
    package:
      name: nodejs
      state: present
...