---
  - name: Install required packages
    become_user: root
    become: True
    include: install-software.yml

  - name: OS preparation
    become_user: root
    become: True  
    include: os-configuration.yml

  - name: Install Taiga
    become_user: taiga
    become: True
    include: install-taiga.yml

  - name: Nginx configuration
    become_user: root
    become: True
    include: nginx.yml

  - name: Start services
    become_user: root
    become: True
    include: services.yml
...