---
  - name: Taiga install | nginx | Copy nginx config file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: Taiga install | nginx | Copy nginx config file
    template:
      src: taiga.conf.j2
      dest: /etc/nginx/conf.d/taiga.conf
      owner: root
      group: root
      mode: '0644'

  - name: Taiga install | nginx | Change directory owner
    file:
      path: /var/lib/nginx
      state: directory
      recurse: Yes
      owner: taiga
      group: taiga
...