---
  - name: Taiga install | os-configuration | Disable SELinux
    selinux:
      state: disabled

  - name: Taiga install | os-configuration | Enable firewalld
    service:
      name: firewalld
      enabled: Yes
      state: restarted

  - name: Taiga install | os-configuration | Add ports to firewalld
    firewalld:
      port: "{{ item }}"
      zone: public
      permanent: Yes
      state: enabled
    with_items:
      - 80/tcp
      - 5672/tcp
      - 15672/tcp
      - 6379/tcp

  - name: Taiga install | os-configuration | Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: Taiga install | os-configuration | Add group taiga
    group:
      name: taiga

  - name: Taiga install | os-configuration | Add the user taiga
    user:
      name: taiga
      create_home: Yes
      groups: 
        - wheel
        - taiga
      password: '$6$.kl4gwnKzvHP5yqk$Cx0GYbcUS8NpdMgYRFXR2Lpz5kqFpVzOPeyewd9kudMl/IMag0qoqxhU.eCWujjeVDflNL3U8xJ91VsSexBol/'

  - name: Taiga install | install-taiga | Copy taiga_events systemd service
    template:
      src: taiga_events.service.j2
      dest: /etc/systemd/system/taiga_events.service
      owner: root
      group: root
      mode: '0644'

  - name: Taiga install | install-taiga | Copy taiga systemd service
    template:
      src: taiga.service.j2
      dest: /etc/systemd/system/taiga.service
      owner: root
      group: root
      mode: '0644'
...