---
  - name: Taiga install | services | Daemon reload
    systemd:
      daemon-reload: yes

  - name: Taiga install | services | Start nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Taiga install | services | Start redis
    service:
      name: redis
      state: started
      enabled: yes

  - name: Taiga install | services | Start taiga.service
    service:
      name: taiga
      state: started
      enabled: yes
    
  - name: Taiga install | services | Start taiga_events.service
    service:
      name: taiga_events
      state: started
      enabled: yes
...