---
  - name: Taiga install | install-taiga | Daemon reload
    systemd:
      daemon-reload: yes

  - name: Taiga install | install-taiga | Start nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Taiga install | install-taiga | Start taiga.service
    service:
      name: taiga
      state: started
      enabled: yes
    
  - name: Taiga install | install-taiga | Start taiga_events.service
    service:
      name: taiga_events
      state: started
      enabled: yes
...