---
  - name: Postgres | pg_install | Install PostgreSQL Repository
    dnf:
      name:  https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present

  - name: Postgres | pg_install | Disable the built-in PostgreSQL module
    command: dnf -qy module disable postgresql

  - name: Postgres | pg_install | Install PostgreSQL packages
    package:
      name: "{{ postgresql_packages }}"
      state: present

  - name: Postgres | pg_install |  Add PostgreSQL ports to firewalld
    firewalld:
      port: "{{ item }}"
      zone: public
      permanent: Yes
      state: enabled
    with_items:
      - 5432/tcp
      - 8008/tcp
      
...